name: Django Unit Tests
on : [push]

jobs:
  django_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3
    steps:
      - uses: actions/checkout@v2
      - name: Instalando dependencias pip
        run: pip install --upgrade
          pip install -r requirements.txt
      - name: Fazendo migracoes
        working-directory: ./backend
        run: python manage.py migrate
      - name: Executar testes
        working-directory: ./backend
        run: python manage.py test --noinput